var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                            o o                 ",
   "                                                   y              xxx           ",
   "                                                           x   x                ",
   "                                                       xxx x!!!x                ",
   "                      v                          xxxxx     xxxxx                ",
   "                                             o                                  ",
   "  x                 y                       xxx                          y  x   ",
   "  x                                     xx           xxx       x         xxxx   ",
   "  x                                     xx      xxx       xxx  x     r   x  x   ",
   "  x          xxx   xxx                xxxx                  x  x   xxxx xx  x   ",
   "  x      xxx x x        x             xxxx                  x  x   x        x   ",
   "  x  @   x x x x     o xx  r        xxxxxx                     x  xx        x   ",
   "  xxxxxxxx xxx xx   xxxxxxxxxxx   xxxxxxxx           x x!!!!!!!xxxx   xxx  xx   ",
   "                x!!!x         x!!!x      x!!!!!!!!!!!x xxxxxxxxx      x     x   ",
   "                x!!!x         x!!!x      x!!!!!!!!!!!x               xx     x   ",
   "                x!!!x         x!!!x      x!!!!!!!!!!!x               xx   o x   ",
   "                xxxxx         xxxxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                      v                                                                                           ",
   "                                                                                                 r                ",
   "              v                                                                                                   ",
   "                                   v               y                                                              ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                    o                                             ",
   "                                                               xxxxxxxxxxx                                        ",
   "                                              x         =  x                                                      ",
   "                              o       xxxx    xxxxxxxxxxxxxx                                                      ",
   "                            xxxxx                                              xxxxxxxxx                          ",
   "      xxxxxxxxxxxxxxxxxx                                                                                          ",
   "   @ x                                                                                     xxxxx           o      ",
   "!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                xxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
 "                                                                                                                ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ","                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                    o                                                                                         ",
   "  x                xxx             o o    x                                        xxx                     x  ",
   "  x               xxxxx       xx         xx                o                      x!v!x          x         x  ",
   "  x                           x      =    x     xxx      xxxxxx                    x x          xvx        x  ",
   "  x          xxxx             xxxxxxxxxxxxx  x       x                 xxxxx                               x  ",
   "  x      @                  xxx           x!!!!!!!!!!!!!!!!!!!!!!!!!!xx    xx                          o   x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
